### ISSUE TITLE
Only run backups when players are connected to the server

### ISSUE THREAD

**Issue by djmattyg007** [SparklingComet/AutoBackup#1]
It would be nice if there was a way to stop backups from happening when there are no players connected to the server. I run a server where, most of the time, there are no players connected and therefore nothing changing. It would be ideal if the plugin could stop taking backups during that time.

**Comment by SparklingComet** [comment]
That’s a very good point, I’ll add a setting to skip the update if fewer than x players are on.

**Comment by SparklingComet** [comment]
Added the requested functionality in #3
