### ISSUE TITLE
Cant backup a world with online players.

### ISSUE THREAD

**Issue by nathanoy** [SparklingComet/AutoBackup#5]
I have encountered that problem with other backup plugins aswell, does someone have a fix? or know how to suppress that error? 
`org.shanerx.backup.zip.zip.ZipException: java.io.IOException: The process cannot access the file because another process has locked a portion of the file`

[error.txt](https://github.com/SparklingComet/AutoBackup/files/7582061/error.txt)

**Comment by SparklingComet** [comment]
Are you using Windows?
https://github.com/SparklingComet/AutoBackup/wiki/Windows

**Comment by SparklingComet** [comment]
for the record: windows compatibility is being considered and may be added in the next releases.
